### brianz aliases
alias ls='ls -G --color=auto'
alias l='ls -lF --color=auto'
alias la='ls -alF --color=auto'
alias lt='ls -lFt --color=auto'
alias p='pwd'
alias v='vim'
alias c='clear'
alias cd..='cd ..'
alias gpp='g++'
alias list_ports='netstat -lnptu'
